public class DataTypes {
    public static void method1(){
        Boolean isActive = true;
        system.debug('Value of isActive='+isActive);
    }
    public static void method2(){
        String fname='Vikrant', lname='Zine';
        system.debug('Name='+fname+ ' ' +lname);
    }
    public static void method3(){
        ID accId = '001dL00000NVUFwQAP';
        system.debug('Id='+accId);
    }
}